# Generated by Django 2.1.5 on 2019-02-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anme', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
