# Generated by Django 2.1.5 on 2019-02-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='anme',
            new_name='name',
        ),
    ]
